
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SpaceHeader from './components/space-header/SpaceHeader'
import SpaceParticles from "./components/space-particles/SpaceParticles"
import { AppContentWidth } from './config/config'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next Space',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
            <main className="flex min-h-screen flex-col items-center justify-between">
                <div className={"py-16 " + AppContentWidth} >
                    <SpaceHeader />
                    <div className="flex justify-center items-center min-h-96">
                        {children}
                    </div>
                    <SpaceParticles />
                    <Toaster
                        position="bottom-center"
                        toastOptions={{
                            className: '',
                            duration: 5000,
                            style: {
                                background: 'var(--color-tertiary)',
                                color: '#fff',
                            }
                        }}
                    />
                </div>
            </main>
        </body>
    </html>
  )
}
